# Generated by Django 3.0.4 on 2020-03-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200322_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('X', 'Archived'), ('C', 'Cancelled'), ('N', 'Not created yet'), ('A', 'Available')], default='m', help_text='Game aviability:', max_length=1),
        ),
    ]
