# Generated by Django 3.0.4 on 2020-04-11 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_auto_20200322_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('X', 'Archived'), ('A', 'Available'), ('C', 'Cancelled'), ('N', 'Not created yet')], default='m', help_text='Game aviability:', max_length=1),
        ),
    ]
